# Generated by Django 4.0.3 on 2022-07-11 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listingBid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.listing'),
        ),
    ]
